### ISSUE TITLE
Is this repo active?

### ISSUE THREAD

**Issue by amir20** [bhurlow/machine-share#19]
What's the status of this repo? Looks like some good PRs have been created but nothing is being maintained. 

I can help out if needed.

**Comment by bhurlow** [comment]
Hi @amir20!

I don't use docker-machine basically at all anymore so this is less useful for me personally.  Happy to merge in anything people need though, indeed looks like I missed a couple of proposed PRs. Is there something you need in particular?

**Comment by amir20** [comment]
I just ran into the #12 bug that took me a while to debug. 

I think you should merge the pull requests at least to help others you who have sent the PR. But also if it's not helpful at all for you, do you plan to deprecate it or potentially give some guidance to people who still do use it? 

Maybe you can ask for another owner if you are not interested to maintain anymore.

**Comment by bhurlow** [comment]
@amir20 I wrote `machine-share` expecting docker-machine to incorporate something like this officially. Sadly it appears this is very much still needed and there are no plans to make sharing docker machines easy :( 

I'm definitely open to somebody taking this over, for now I can move forward with merging the existing PRs

**Comment by amir20** [comment]
Cool. Then let's close. 

I agree about the need for this. I don't know what the plan is for docker.

**Comment by bhurlow** [comment]
I've stopped waiting for docker :) feel free to submit PRs

**Comment by desmap** [comment]
> I don't use docker-machine basically at all anymore 

@bhurlow what do you use instead now? Do you rather deploy to k8s clusters? This is what I am thinking about.

**Comment by bhurlow** [comment]
@desmap using AWS ECS currently
