### ISSUE TITLE
Import breaks empty string and URL config settings.

### ISSUE THREAD

**Issue by alrik** [bhurlow/machine-share#22]
On import all empty string config values become "." due to `path.join('') === '.'`

So a config of

```json
{
    "ConfigVersion": 3,
    "Driver": {
        "CaCert": "",
        "DomainID": "",
        "DomainName": ""
    }
}
```
will become 
```json
{
    "ConfigVersion": 3,
    "Driver": {
        "CaCert": ".",
        "DomainID": ".",
        "DomainName": "."
    }
}
```

That will break any further `docker-machine` operations:

```sh
$ docker-machine ls
Error attempting call to get driver name: connection is shut down
NAME           ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER    ERRORS
myMachine      -                 Error                 Unknown   read .: is a directory
```

I'll submit a PR asp.

**Comment by alrik** [comment]
@bhurlow I think empty strings are not the only problem, but also urls:
`path.join('https://openstack-host.xy/2.0') => 'https:/openstack-host.xy/2.0'`

What do you think about only path-joining config settings, that contain {{HOME}} in [import.js](https://github.com/bhurlow/machine-share/blob/master/import.js#L61)?
Could that possibly break windows compatibility?

**Comment by bhurlow** [comment]
@alrik Hi! Ok thanks

**Comment by colthreepv** [comment]
Is this issue still reproducible?

I thought I fixed most, or even all the windows/unix pathing problems with #18

**Comment by alrik** [comment]
I think this issue can be closed :)
