### ISSUE TITLE
Permissions aren't right after import

### ISSUE THREAD

**Issue by bodymindarts** [bhurlow/machine-share#5]
Sshing into an imported machine fails.

```
machine-import ${machine-name}.zip
docker-machine ssh ${machine-name}
Permissions 0644 for '/root/.docker/machine/machines/<machine-name>/id_rsa' are too open.
```

Fixing the permission like so:

```
chmod 0600 /root/.docker/machine/machines/${machine_name}/id_rsa
```

resolves the issue. Could this be taken care of during import?

**Comment by colthreepv** [comment]
[They should be, now](https://github.com/bhurlow/machine-share/blob/master/import.js#L40)

**Comment by bhurlow** [comment]
is this resolved? appears to be

**Comment by colthreepv** [comment]
I think so, vote for close

**Comment by bodymindarts** [comment]
I haven't checked it and am not working on a project that relies on this at the moment, so I don't really have the time to check it either. But if you consider it resolved seems fine to close it.
